### ISSUE TITLE
It's not showing image which i upload

### ISSUE THREAD

**Issue by Lokesh2096** [aldrashan/angular-tui#1]

**Comment by baseq** [comment]
Add a wrapper div and set a css height like this:
```css
.container {
    height: 800px;
}
```
```html
<div class="container">
    <tui-image-editor [options]="this.options"></tui-image-editor>
</div>
